### ISSUE TITLE
/pay command

### ISSUE THREAD

**Issue by moo-man** [CatoThe1stElder/WFRP-4th-Edition-FoundryVTT#246]

**Comment by JiDW** [comment]
- [x] Add an Availability table
- [x] Add the ability to Send to chat a Compendium item entry
- [x] Roll for item availability
- [x] Add a button to get some change
- [x] Add a /pay command
- [x] Add a "Pay" contextual action on item cards in chat

### Add an Availability table
As per the rulebook (p290), add a table to roll an Availability Test. Like the "Weather" table in EiS, when rolled without any args, it should ask for the settlement size (Village, Town, City).
It should then ask for the rarity of the item (Common, Scarce, Rare).
Result should give the following informations:

- In stock: Yes/No
- Quantity available: 1d10+settlement size modifier (rulebook p290-291) rounded up

Arguments can be passed to the table: Size and Rarity
The Table Modifier Menu have to be available for this table.

### Roll for item availability
On an item card in the chat, add a contextual menu (right click) roll the Availability Table with prepopulated arguments from the item card.

### Add the ability to Send to chat a Compendium item entry
This can allows GMs to easily share informations on an item that a player want to buy, or a service like a room for the night.

### Add a button to get some change
In the Trapping tab of the character sheet, add a button to change the quantity of each money in order to maximize GC, then SS, then BP.
Some example:
120bp, 12ss, 0gc => 0bp, 2ss, 1gc
9bp, 75ss, 1gc => 9bp, 15ss, 4gc
A GM could allow its players to use it when they are currently in a shop or a bank. It is also useful for the /pay command.

Unsure: If the character do not have some of the 3 money trappings at all (not even at 0 quantity), this button could maybe add the missing money?

![Annotation 2020-04-13 185051](https://user-images.githubusercontent.com/581736/79140092-be18b980-7db7-11ea-8593-b0e8f65bd15e.jpg)

### Add a /pay command
The /pay command is used to modify the 3 money trappings (gc, ss and bp).
Usage: 
/pay 3gc2bp
/pay 450bp
/pay 2ss12bp4gc

This command modifies the quantity of each money on the following rules:
- Trying first to remove the exact amount of each money given to the command
- If there is not enough money, the command will try to calculate everything into BP then try to pay the price. If it succeed, it will then use the "make change" feature to give the player the lowest quantity of coins possible.

Ease of use: the command tries its best to understand the arguments.
As an example, this would still work:
/pay 51GC 8BP 7 ss

### Add a "Pay" contextual action on item cards in chat
Under the "Roll for availability" action, a player can directly pay the full price of a trapping entry.
While the price can't be negotiated, it can still be useful for very cheap trappings like a beer, a room or a meal. The GM could use this for other means too, like creating a "Fine" item to ask for payment when the group's thief get caught by the guards. 

Note that "paying" an item does not add it to the character inventory. However, the player can then drag&drop the item card from the chat to its sheet.

![Annotation 2020-04-13 185036](https://user-images.githubusercontent.com/581736/79140087-bd802300-7db7-11ea-9a50-81f564e79ff4.jpg)

What do you think about all of this?
Any critics, issues, ideas?

**Comment by moo-man** [comment]
@JiDW great work, I like the look of this, I will add that I made money "Items" specifically so that different currencies could be used. I think it would be good to add an "abbreviation" field to the money item template so this can be supported for any type of money.

**Comment by moo-man** [comment]
Additional Ideas

1. Maybe place 2 buttons at the bottom of the item chat card (similar to character generation) for "Availability" and "Pay"

2. Instead of a 'fine' item, maybe make it a chat command? `/pay 10bp` when coming from a GM will show a very simple chat card that has a button players can click on to automatically pay.

**Comment by JiDW** [comment]
Yes, buttons are better. Could be done for "apply damage" too by the way, it's more user friendly, I agree.
Good idea for the GM /pay command, I will look into that once I'm done with everything else!
And yes for abbreviation support, I'll definitely do it if I found an easy way to make it work with everything else, not sure how tho.

**Comment by moo-man** [comment]
In your /pay command, when arguments aren't recognized, make sure to throw an error detailing what the parser is looking for, ideally list out 
```
/pay 3gc2bp
/pay 450bp
/pay 2ss12bp4gc
```
